### ISSUE TITLE
TICTeC Privacy Policy - review & deploy

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/ainow#104]
Text is [here](https://docs.google.com/document/d/1_LPWPeBff9uxL6O4EsCGpByPWCJRY-s9Qzt5VlNBYW0/edit#) (visible to mySoc staff only) - needs some finalising and then can it go somewhere reasonably visible? GDPR related, of course.

**Comment by MyfanwyNixon** [comment]
This has been discussed and agreed now so I think we're ready to deploy it please!

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/ainow/pull/108

**Comment by zarino** [comment]
Deployed! http://tictec.mysociety.org/privacy/
