### ISSUE TITLE
Fixture files need updating, to reflect new slot/session structure and date format

### ISSUE THREAD

**Issue by zarino** [mysociety/ainow#121]
https://github.com/mysociety/ainow/commit/3d79d8764852f4bf3a120be38ba18005dcda41b9 split slots into slots and sessions, but the fixture slots in `conference/fixtures/sample_data.json` were never updated.

It also changed slot `start` and `end` fields to be datetimes rather than just dates. Again, this wasn’t reflected in the fixtures.

This means `vagrant up` fails right at the end of provisioning, because slot dates are in the wrong format, and slots no longer have `name` attributes, and `./manage.py loaddata` doesn’t know what to do.

A workaround in the meantime is to just ignore the provisioning failure, and create your own `schedule`, manually, via the Django admin UI.

But it’s a shame to have fixtures there that can’t be used.

**Comment by chrismytton** [comment]
The sample data loading step of `vagrant up` was removed in https://github.com/mysociety/ainow/pull/138. A better method of pulling down a copy of the live database was added in https://github.com/mysociety/ainow/pull/141.
