### ISSUE TITLE
Set up ainow@ and info@ email addresses so that mariah et al can send and receive mail from them.

### ISSUE THREAD

**Issue by stevenday** [mysociety/ainow#18]
We currently have two aliases setup: info@ and rsvp@. It seems like the latter is no longer needed, but we need to add a third: ainow@.

At the moment these just forward info on, but we need to be able to send mail from them as well, ideally via a new, shared, gmail inbox.

**Comment by stevenday** [comment]
I'm going to talk to @hazelesque about this tomorrow to figure out how to set it up.

**Comment by hazelesque** [comment]
Thanks @stevenday, I'm working on this now.

**Comment by hazelesque** [comment]
Per https://github.com/mysociety/sysadmin/issues/733 this should now be ready for Steve to hand over.
