### ISSUE TITLE
Homepage view will break during the conference and afterwards

### ISSUE THREAD

**Issue by stevenday** [mysociety/ainow#67]
There's still code for AINow in `HomeView` which had a livestream during the conference and switched the homepage afterwards to reference some specific talks. This will break the site (because the presentations it references don't exist), so we'll need to do something about this before then.

**Comment by struan** [comment]
Fixed in https://github.com/mysociety/ainow/commit/c29cc50ea5a738318d3c287acf5bb1fb5d26857d
