### ISSUE TITLE
Transfer AINow domain names to client

### ISSUE THREAD

**Issue by abibroom** [mysociety/ainow#97]
We registered artificialintelligencenow.org and artificialintelligencenow.com for the client; ideally they should have these under their own control and be paying for them directly.

**Comment by davea** [comment]
I've emailed them today to point out that any transfer needs to be initiated by their new registrar. I've also removed the transfer lock on both domains.

**Comment by abibroom** [comment]
@davea did anything result from your email? These two domains expire on 25th April and I currently have no intention of renewing them, so the clock is ticking for them to do something about it. Can you please let them know?

**Comment by davea** [comment]
I've just checked and the domain transfers have been completed, so we don't need to take any further action.

**Comment by sagepe** [comment]
Just to add that I've also removed the zones from our hosts and Prolateral.
