### ISSUE TITLE
Make final changes to site to close off 2017 work

### ISSUE THREAD

**Issue by jukesie** [mysociety/ainow#98]
There are a *few* changes needed to the AI:Now site that require developer intervention I believe - I can resolve any of the content issues once this is done.

See this 'deck' for UI changes

https://docs.google.com/presentation/d/1y8VKEydXuxKmRnVTk9Z_dC-l1uFHMA4mWJfzBounCw0/edit#slide=id.g24afae19e8_0_44

This doc for copy changes: https://docs.google.com/document/d/1rzL5sSAZUyF-3HE4tjXu6IRe4ZO_ngJRWdFK1XaYLtg/edit# – all outlined also below.

**Comment by dracos** [comment]
All done, pretty much, bar the following:
- [ ] Bits where they haven't given any text/links
- [ ] Front page FB link - no idea what it is
- [x] 2016/7 page - summary & topic sections - what links are these meant to contain, to what?
- [ ] 2017 lightning talks all need long descriptions (don't think short shown anywhere)
- [ ] Nav link to 2017 report (needs editing file)

Design bits:
- [ ] About page "Photo banner coming"
- [x] 2017 symposium page, replace banner photo with this photo: https://drive.google.com/open?id=0B8GxCNOdkyIVVFVpako2WVpnaHM Photo must attribute credit to the photographer, ideally in small letters on the righthand side “Photograph by Mim Adkins” (don't have access)
- [x] 'view all' on symposium page after each talks section and attendees section not great
- [x] Footer colour bottom of https://artificialintelligencenow.com/schedule/conference/presentations doesn't work with logos, why is it not the old off white (gray-lighter)?
- [ ] 2017 page, "would be great to have white text on the photo, justified left that read:  “AI NOW 2017 SYMPOSIUM” Then in smaller letters underneath: “July 10th, MIT Media Lab, Cambridge, MA”"
- [x] https://artificialintelligencenow.com/schedule/conference - Photo must attribute credit to the photographer, ideally in small letters on the righthand side “Photograph by Kate Reeder”.
- [ ] Same page, "would be great to have white text on the photo, justified left that read:  “AI NOW 2016 SYMPOSIUM” Then in smaller letters underneath: “July 7th, Skirball Center for the Performing Arts, New York, NY”"

**Comment by dracos** [comment]
Copy changes, part 2:

- [ ] AI NOW 2017 SYMPOSIUM PAGE
    - [ ] Replace banner photo with this photo: https://drive.google.com/open?id=0B8GxCNOdkyIVVFVpako2WVpnaHM Photo must attribute credit to the photographer, ideally in small letters on the righthand side “Photograph by Mim Adkins” 
    - [ ] Would be great to have white text on the photo, justified left that read:  “AI NOW 2017 SYMPOSIUM” Then in smaller letters underneath: “July 10th, MIT Media Lab, Cambridge, MA”
    - [ ] Intro paragraph under photo w title : “The AI Now Symposium is an annual event designed to address the biggest challenges we face as AI moves further into our everyday lives. The 2017 Symposium brought together over 100 leading experts from industry, academia, civil society, and government to share ideas for technical design, research and policy directions. Discussions this year focused on the application of AI in the near-term across four key themes: Rights and Liberties, Labor and Automation, Bias and Inclusion, and Safety and Ethics.” “These experts spent a day in closed-door talks and discussion, then joined an evening program that was free and open to the public.” “The Symposium is hosted by the AI Now Initiative with generous support in 2017 from the AI Ethics and Governance Fund, the John D. and Catherine T. MacArthur Foundation, and the MIT Media Lab.” Twitter logo with “@ainowinitiative #ainow2017” hyperlinked 
    - [ ] “Summary report and recommendations “Here we offer a summary of AI Now 2017, reviewing the core domains and key insights, with an eye to highlighting recent developments and new research.”
    - [ ] “Talks”
        - [ ] Experts Workshop. Thumbnails with a button that links to a page with all videos. Link to all Experts Workshop youtube files (with the video titles as we’d like them to be displayed). Link to all Experts Workshop video files: 
        - [ ] Public Symposium. Thumbnails with a button that links to a page with all videos . Link to all Symposium youtube files (with the video titles as we’d like them to be displayed). Link to all Symposium video files: 
    - [ ] “Attendees and Speakers”. Layout should be the same as previous sections - with thumbnails of a few photos and then a button to “all attendees and speakers” . The button “all attendees and speakers should link to this page: https://artificialintelligencenow.com/schedule/2017-experts-workshop/attendees . Title for this page should be upated to AI Now 2017 Attendees & Speakers” and delete the line that reads “Attendees & Speakers confirmed to date.”
    - [ ] “Program”. Keep the program same as before  -see deck 
- [ ] AI NOW 2016 SYMPOSIUM PAGE
    - [ ] Add photo banner. Add the photo that is currently on the AI Now 2017 page (see slide deck. Photo must attribute credit to the photographer, ideally in small letters on the righthand side “Photograph by Kate Reeder” 
    - [ ] Would be great to have white text on the photo, justified left that read:  “AI NOW 2016 SYMPOSIUM” Then in smaller letters underneath: “July 7th, Skirball Center for the Performing Arts, New York, NY”
    - [ ] Intro paragraph under photo w title : “The 2016 AI Now Symposium on the Social and Economic Impact of Artificial Intelligence Technologies was the first annual AI Now symposium, co-hosted by AI Now, NYU, and the Obama White House's Office of Science and Technology. The event was part of the White House's Preparing for the Future of Artificial Intelligence Initiative, which convened four separate workshops exploring AI's future impacts. To explore the social and economic implications, AI Now 2016 gathered 100 leading experts on looking at AI's effect on inequality, labor, health, and ethics. These experts spent a day in closed-door talks and discussion, then joined an evening program open to the public. ”
    - [ ] “Summary report and recommendations” “Here we offer a summary of AI Now, reviewing its core themes and key insights, and offering high-level recommendations for stakeholders engaged in the production, use, governance, and assessment of AI in the near-term.”
    - [ ] “Topic Primers”. “These primers were distributed to attendees of the AI Now Expert Workshop before the event. They were created to provide thorough overviews of the opportunities and issues posed by the introduction of AI across AI Now's four focus areas.”
    - [ ] “Talks”  (follow format like on this page) https://web.archive.org/web/20170108234505/https://artificialintelligencenow.com/
        - [ ] Experts Workshop . Thumbnails with a button that links to a page with all videos . You should have videos on file - please see link above
        - [ ] Public Symposium . Thumbnails with a button that links to a page with all videos . You should have videos on file, please see link above
    - [ ] “Attendees and Speakers” . Layout should be the same as previous sections - with thumbnails of a few photos and then a button to “all attendees and speakers” . The button “all attendees and speakers should link to this page: https://artificialintelligencenow.com/schedule/workshop/attendees . On this page update the title to “AI Now 2016 Attendees & Speakers” and delete the line that says “Attendees & Speakers confirmed to date.”

**Comment by dracos** [comment]
Considering done
